### ISSUE TITLE
Enable sellers to update quantity of the products

### ISSUE THREAD

**Issue by rhulucas** [rhulucas/homework1#1]
**User story**
As a seller, I tend to make more products or decrease the inventory due to damaged products, so I would like to update the quantity of products for sell.

*persona: seller who tend to recall the damaged product from warehouse.
*feature: seller updates the quantity of inventory online.
*business value: increasing sales and decrease the negative feedback from buyer

**Task List**

- [x] Make sure the data base schemes handle inventory quantity updates
- [ ] Create HTML view for updating inventory quantity
- [ ] Connect the HTML view the database/backend to finish the function ...

**Acceptance Criteria**
1. only at the beginning of the month: count the inventory.
2. works only for Chrome, iOS .

**Acceptance Tests**
1. the seller should be able to update existing product quantity.
2. the seller should be able to remove existing product quantity.
3. the seller should be able to add new product quantity.
